"""Write paper/numbers.tex, the numbers the paper quotes from the long runs.

The paper reads these as LaTeX macros, so the values in the text come straight from
results/ and cannot drift from the archived data.
"""

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def sig(x, n=3):
    if x == 0:
        return "0"
    digits = n - 1 - int(math.floor(math.log10(abs(x))))
    return f"{round(x, digits):.{max(digits, 0)}f}"


def sci(x, n=3):
    """A number in siunitx form, so the paper typesets it consistently."""
    return f"\\num{{{x:.{n - 1}e}}}" if (abs(x) < 1e-2 or abs(x) >= 1e4) else f"\\num{{{sig(x, n)}}}"


def main():
    post = {round(r["coverage"], 2): r for r in
            json.loads((ROOT / "results" / "firstpass_postmortem.json").read_text())}
    lat = json.loads((ROOT / "results" / "lattice_check.json").read_text())["summary"]
    ninety, eighty_five = post[0.9], post[0.85]

    expected = ninety["expected_events_transient"]
    note = (f"so a run that saw none had a probability of "
            f"{sig(ninety['poisson_p_zero_transient'], 2)}")
    verdict = "a fluctuation in too short a window, on a surface that was never dead"

    macros = {
        "PMverdict": verdict,
        "PMexactNinety": sci(ninety["exact_stationary_tof"], 4),
        "PMwindowNinety": sci(ninety["window"], 3),
        "PMburnNinety": sci(ninety["burn_in_end"], 3),
        "PMexpectedNinety": sci(expected, 3),
        "PMtransientNote": note,
        "PMlongBurn": sig(ninety["long_run"]["burn"], 2),
        "PMlongMeasure": sig(ninety["long_run"]["measure"], 2),
        "PMlongNinety": f"{sci(ninety['long_run']['tof'], 4)}$\\pm$\\num{{{sig(ninety['long_run']['sem'], 2)}}}",
        "PMlongZNinety": sig(abs(ninety["long_run"]["z"]), 2),
        "PMfirstEightyFive": sci(eighty_five["first_pass_tof"], 3),
        "PMobservedEightyFive": str(eighty_five["observed_events"]),
        "PMexpectedEightyFive": sci(eighty_five["expected_events_transient"], 3),
        "PMstationaryEventsEightyFive": sci(eighty_five["expected_events_stationary"], 2),
        "PMratioEightyFive": sig(eighty_five["first_pass_tof"] / eighty_five["exact_stationary_tof"], 2),
        "PMpZeroNinety": sig(ninety["poisson_p_zero_transient"], 2),
        "PMexactEightyFive": sci(eighty_five["exact_stationary_tof"], 4),
        "PMlongEightyFive": (f"{sci(eighty_five['long_run']['tof'], 4)}$\\pm$"
                             f"\\num{{{sig(eighty_five['long_run']['sem'], 2)}}}"),
        "LVruns": str(lat["runs"]),
        "LVchi": sig(lat["chi2"], 3),
        "LVchip": sig(lat["chi2_p_value"], 2),
        "LVmaxz": sig(lat["max_abs_z"], 3),
        "LVmaxdev": f"{100 * lat['max_rel_dev']:.2f}\\%",
    }
    lines = ["% Generated by src/paper_numbers.py from results/. Do not edit by hand."]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in macros.items()]
    out = ROOT / "paper" / "numbers.tex"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"  wrote {out.relative_to(ROOT)}")
    for k, v in macros.items():
        print(f"    {k:20s} {v}")


if __name__ == "__main__":
    main()
